version: '3.8'

services:
  accident-injury-prediction-service:
    image: accident-injury-prediction-service:v1
    ports:
      - "9696:9696"
    volumes:
      - ./secrets/prediction_server:/run/secrets:ro
    env_file: served_model_env_vars
    restart: always
  mlflow:
    build:
      context: .
      dockerfile: ./code/mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlflow:/home/mlflow/
      - ./secrets/mlflow:/run/secrets:ro
    networks:
      - app-network
  prefect:
    build:
      context: .
      dockerfile: ./code/prefect.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./data/prefect:/database/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge